### ISSUE TITLE
Method Promise.prototype.then called on incompatible receiver [object Object]

### ISSUE THREAD

**Issue by killlowkey** [xwj-vic/yapi#10]
## 版本号
xuweijie1015/yapi:latest

## 什么问题
使用接口中的高级 Mock 脚本方式进行 mock，会出现 Method Promise.prototype.then called on incompatible receiver [object Object]。
堆栈信息如下所示
```
Error: Error: Method Promise.prototype.then called on incompatible receiver [object Object]
at Safeify.handleScriptResult (/yapi/vendors/node_modules/safeify/lib/Safeify.js:189:34)
at Safeify.handleScriptDone (/yapi/vendors/node_modules/safeify/lib/Safeify.js:178:14)
at Safeify.onWorkerDone (/yapi/vendors/node_modules/safeify/lib/Safeify.js:164:14)
at ChildProcess.Safeify.onWorkerMessage (/yapi/vendors/node_modules/safeify/lib/Safeify.js:55:33)
at ChildProcess.emit (events.js:310:20)
at emit (internal/child_process.js:876:12)
at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

## 如何复现此问题
接口信息
![image](https://github.com/xwj-vic/yapi/assets/41176828/43cfbb99-44a7-4fdb-b0df-1163992b83df)

mock 脚本
![image](https://github.com/xwj-vic/yapi/assets/41176828/7f8aa9a6-bffc-40f6-a5a7-bb3a2084d165)

运行结果
![image](https://github.com/xwj-vic/yapi/assets/41176828/5bb7399f-553c-4ae4-a093-440cf853b9c2)

## 什么浏览器
chrome

## 什么系统（Linux, Windows, macOS）
windows

**Comment by xwj-vic** [comment]
好的，我排查一下

**Comment by xwj-vic** [comment]
已解决，请拉最新镜像

**Comment by killlowkey** [comment]
> 已解决，请拉最新镜像

感谢，拉取后能正常使用
